import express from "express";
import { uploadClientImage } from "../middlewares/multer.js";
import clientControllers from "../controllers/clients.js";
const router=express.Router();
router.get("/get-clients", clientControllers.getClients);
router.post("/add-client",uploadClientImage, clientControllers.addClient);
router.get("/get-client/:client_id", clientControllers.getClientById);
router.put("/update-client/:client_id",uploadClientImage, clientControllers.updateClient);
router.delete("/delete-client/:client_id", clientControllers.deleteClient);
export default router;